# -*- makefile-bsdmake -*-
#
#	Makefile.main - input for BSD Make
#
# Copyright (C) 2025 Greg A. Woods - This work is licensed under the Creative
# Commons Attribution-ShareAlike 4.0 International License.  To view a copy of
# the license, visit <URL:http://creativecommons.org/licenses/by-sa/4.0/>, or
# send a letter to:  Creative Commons, PO Box 1866, Mountain View, CA 94042, USA

# This file should be usable as the main Makefile in a full BSD source tree.

# adjust these as necessary (e.g. set them on the make command-line)
PATH_SYSCONFDIR ?=	/etc		# location of configuration files
PATH_FINGER ?=		/usr/bin/finger	# location of the finger(1) program

# You shouldn't have to change anything below here.

# xxx Some of the settings below could be moved to a Makefile.project file, but
# then it would need to be renamed to Makefile.inc if this project were to be
# used in a BSD source tree.

PACKAGE_NAME =	fingerd

# N.B.:  Remember to update DISTNAME in Makefile.pkgsrc when updating these!
#
PACKAGE_MAJOR =	2
PACKAGE_MINOR =	0
PACKAGE_MICRO =	0

PACKAGE_VERSION =	${PACKAGE_MAJOR}.${PACKAGE_MINOR}.${PACKAGE_MICRO}

# this project is all pure standard C
#
CSTD = c99
CWARNFLAGS += -pedantic

# N.B.:  normally this would/is set by the parent source directory's
# Makefile.inc file (which, if it exists, is always sourced by <bsd.prog.mk>),
# but since that doesn't exist for a stand-alone project, or in pkgsrc, we set
# it here (possibly overriding the independent project's Makefile.inc setting).
#
BINDIR :=	/libexec

_PACKAGE_NAME =		"${PACKAGE_NAME}"
CPPFLAGS += -DPACKAGE_NAME=${_PACKAGE_NAME:Q}
_PACKAGE_VERSION =	"${PACKAGE_VERSION}"
CPPFLAGS += -DPACKAGE_VERSION=${_PACKAGE_VERSION:Q}

_PATH_FINGER =		"${PATH_FINGER}"
CPPFLAGS += -D_PATH_FINGER=${_PATH_FINGER:Q}
_PATH_SYSCONFDIR =	"${PATH_SYSCONFDIR}"
CPPFLAGS += -D_PATH_SYSCONFDIR=${_PATH_SYSCONFDIR:Q}

# Fingerd only supports POSIX IEEE Std 1003.1-2001, IEEE Std 1003.2-1992, and it
# should still be C89 compatible.
#
# Fingerd requires a 4.4BSD compatible syslog(3) [with openlog(3)]; as well as
# libwrap [XXX currently we are using the old compatibility function rfc931()
# from libwrap, but may eventually use ident_lookup(3) from libident instead]
#
# However N.B.:  actually the code in here is still partly pre-c89, but most
# compilers begrudgingly accept it!
#
CSTD=			c89

# XXX also use ident_lookup(), from libident?
#
CPPFLAGS += -DHAVE_LIBWRAP
LDADD += -lwrap
#DPADD += ${LIBWRAP}	# in a standalone build this will generate an error

PROG =	fingerd

SRCS =	fingerd.c access.c misc.c version.c

MAN =	fingerd.8

DOCS =		AUTHORS COPYING NEWS README THANKS ToDo

# XXX these should also be put in ${PREFIX}/share/examples/${PACKAGE_NAME} for packages
#
CONFIGFILES=	samples/fingerd.acl \
		samples/fingerd.motd \
		samples/fingerd.users

version.o: Makefile

fingerd.o: Makefile

# note the care taken to not change the target unless it is really different
# might cause the command to always run (e.g. if Makefile is newer than
# fingerd.8).  If this bothers you then run "make -t fingerd.8" to force the
# target file to be up to date.
#
fingerd.8: fingerd.8.in Makefile
	sed -e 's|@PATH_FINGER@|${PATH_FINGER}|' \
	    -e 's|@PATH_SYSCONFDIR@|${PATH_SYSCONFDIR}|' \
	    -e 's|@PACKAGE_NAME@|${PACKAGE_NAME}|' \
	    -e 's|@PACKAGE_VERSION@|${PACKAGE_VERSION}|' \
	< ${.CURDIR}/fingerd.8.in > ${.TARGET}.tmp && \
	cmp -s ${.TARGET}.tmp ${.TARGET} || mv ${.TARGET}.tmp ${.TARGET}

CLEANFILES += fingerd.8

docs: .PHONY ${DOCS} ${MAN}

# N.B.:  ATTENTION SYSTEM INTEGRATORS:
#
# In NetBSD the installation of configuration files is done at "make
# distribution" time (which is part of "make release" but also allowed
# separately).  This step is optimised so that it doesn't have to descend
# recursively through every source directory and Makefile in the project, but as
# a result that means there must be a hook in src/etc/Makefile.  It could also
# be done with <bsd.files.mk>, which is then triggered with the default
# "configinstall" target (they are already listed as CONFIGFILES), but again
# that still needs the hook in src/etc/Makefile!
#
# So, to avoid further portability complications with also including
# <bsd.files.mk> we'll just provide a "distribution" target here and any systems
# integrators will have to either ensure it gets called at the right time in
# their release process, or conversely add ".include <bsd.files.mk>" below and
# make sure that a "make configinstall" is done in this source directory.
#
distribution:	# install sample configuration files
distribution: .PHONY
.for _F in ${CONFIGFILES:O:u}
	${INSTALL} -c -o root -g wheel -m 644 ${.CURDIR}/${_F} ${DESTDIR}/etc
.endfor

# just make sure it runs and can display its command-line help
regress: all
	@fingerd -? || true

.include <bsd.prog.mk>

#
# Local Variables:
# eval: (make-local-variable 'compile-command)
# compile-command: (concat "BUILD_DIR=build-$(uname -s)-$(uname -p); mkdir -p ${BUILD_DIR}; MAKEOBJDIRPREFIX=$(pwd -P)/${BUILD_DIR} " (default-value 'compile-command) " -j 8 LDSTATIC=-static obj depend all")
# End:
#
